# These are supported funding model platforms

github: [e-m-b-a]
ko_fi: embafirmwareanalyzer
buy_me_a_coffee: securefirmware
custom: ["https://www.buymeacoffee.com/securefirmware", "https://www.patreon.com/user?u=84705980", "https://emba-firmware-analyzer.myspreadshop.de/"]
