# These are supported funding model platforms

github: [e-m-b-a]
custom: ["https://www.buymeacoffee.com/securefirmware", "https://www.patreon.com/user?u=84705980", "https://www.spreadshirt.de/shop/user/emba+firmware+analyzer/#?affiliateId=1257693"]
